services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: negative-detector
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: pass33
      POSTGRES_DB: message
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
